config/routes.rb
Mysecurity::Application.routes.draw do

  scope '/soft/relevamiento' do

  get "relevamientos/sitio_en_construccion", to: "relevamientos#sitio_en_construccion"

  resources :relevamientos

    devise_for :users, :path => 'user'

  

  root :to => "relevamientos#sitio_en_construccion"
  end
end

app/models/relevamiento.rb
class Relevamiento < ActiveRecord::Base
  attr_accessible :activo_pasivo_aux, :activo_pasivo_docente, :calle, :cant_cuadras, :depto, :distancia_km, :escuela_id, :frente_alumnos, :grado_anio_alumno, :grado_docente, :localidad_id, :lugar_auxiliares, :nivel_id, :nombre_y_apellido, :nro, :nro_documento, :piso, :regular, :rol, :servicio_transporte, :telefono_contacto, :tipo_de_documento_id, :tipo_gestion_id, :turno_docente

  belongs_to :tipo_de_documento
  belongs_to :escuela
  belongs_to :nivel
  belongs_to :tipo_gestion
  belongs_to :localidad

  validates :nombre_y_apellido, :presence => true
  validates :nro_documento, :presence => true, uniqueness: true

end

app/controllers/relevamientos_controller.rb
class RelevamientosController < ApplicationController
  # GET /relevamientos
  # GET /relevamientos.json
  def index
    @relevamientos = Relevamiento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @relevamientos }
    end
  end

  # GET /relevamientos/1
  # GET /relevamientos/1.json
  def show
    @relevamiento = Relevamiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relevamiento }
    end
  end

  # GET /relevamientos/new
  # GET /relevamientos/new.json
  def new
    @relevamiento = Relevamiento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relevamiento }
    end
  end

  # GET /relevamientos/1/edit
  def edit
    if session["id_actual"].to_s == params[:id] then
      @relevamiento = Relevamiento.find(params[:id])
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Usted no puede editar este relevamiento" }
        format.json { head :no_content }
      end
    end
  end

  # POST /relevamientos
  # POST /relevamientos.json
  def create
    @relevamiento = Relevamiento.new(params[:relevamiento])

    respond_to do |format|
      if @relevamiento.save
        session["id_actual"] = @relevamiento.id
        format.html { redirect_to @relevamiento, notice: 'Relevamiento ha sido creado correctamente.' }
        format.json { render json: @relevamiento, status: :created, location: @relevamiento }
      else
        format.html { render action: "new" }
        format.json { render json: @relevamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /relevamientos/1
  # PUT /relevamientos/1.json
  def update
    @relevamiento = Relevamiento.find(params[:id])

    respond_to do |format|
      if @relevamiento.update_attributes(params[:relevamiento])
        format.html { redirect_to @relevamiento, notice: 'Relevamiento ha sido actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relevamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relevamientos/1
  # DELETE /relevamientos/1.json
  def destroy
    @relevamiento = Relevamiento.find(params[:id])
    @relevamiento.destroy

    respond_to do |format|
      format.html { redirect_to relevamientos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/relevamientos_helper.rb
module RelevamientosHelper
end

app/views/relevamientos/edit.html.erb
<h1>Editando relevamiento</h1>

<%= render 'form' %>

app/views/relevamientos/index.html.erb
<% if user_signed_in? then %>

<h1>Listing relevamientos</h1>

<table class="table table-striped">
  <tr>
    <th>Nombre y apellido</th>
    <th>Tipo de documento</th>
    <th>Nro documento</th>
    <th>Escuela</th>
    <th>Nivel</th>
    <th>Tipo gestion</th>
    <th>Localidad</th>
    <th>Calle</th>
    <th>Nro</th>
    <th>Piso</th>
    <th>Depto</th>
    <th>Grado anio alumno</th>
    <th>Regular</th>
    <th>Cant cuadras</th>
    <th>Distancia km</th>
    <th>Servicio transporte</th>
    <th>Telefono contacto</th>
    <th>Rol</th>
    <th>Activo pasivo docente</th>
    <th>Frente alumnos</th>
    <th>Grado docente</th>
    <th>Turno docente</th>
    <th>Activo pasivo aux</th>
    <th>Lugar auxiliares</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relevamientos.each do |relevamiento| %>
  <tr>
    <td><%= relevamiento.nombre_y_apellido %></td>
    <td><%= relevamiento.tipo_de_documento_id %></td>
    <td><%= relevamiento.nro_documento %></td>
    <td><%= relevamiento.escuela_id %></td>
    <td><%= relevamiento.nivel_id %></td>
    <td><%= relevamiento.tipo_gestion_id %></td>
    <td><%= relevamiento.localidad_id %></td>
    <td><%= relevamiento.calle %></td>
    <td><%= relevamiento.nro %></td>
    <td><%= relevamiento.piso %></td>
    <td><%= relevamiento.depto %></td>
    <td><%= relevamiento.grado_anio_alumno %></td>
    <td><%= relevamiento.regular %></td>
    <td><%= relevamiento.cant_cuadras %></td>
    <td><%= relevamiento.distancia_km %></td>
    <td><%= relevamiento.servicio_transporte %></td>
    <td><%= relevamiento.telefono_contacto %></td>
    <td><%= relevamiento.rol %></td>
    <td><%= relevamiento.activo_pasivo_docente %></td>
    <td><%= relevamiento.frente_alumnos %></td>
    <td><%= relevamiento.grado_docente %></td>
    <td><%= relevamiento.turno_docente %></td>
    <td><%= relevamiento.activo_pasivo_aux %></td>
    <td><%= relevamiento.lugar_auxiliares %></td>
    <td><%= link_to 'Show', relevamiento %></td>
    <td><%= link_to 'Edit', edit_relevamiento_path(relevamiento) %></td>
    <td><%= link_to 'Destroy', relevamiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relevamiento', new_relevamiento_path %>

<% else %>
  <%= link_to 'Cargar nuevo relevamiento', new_relevamiento_path, :class => "btn btn-success" %>
<% end %>

app/views/relevamientos/new.html.erb
<%= image_tag "logo.png" %>
<hr/>
<h2>Boleto Educativo Gratuito</h2>
</br>


<%= render 'form' %>

app/views/relevamientos/show.html.erb
<p id="notice"><%= notice %></p>

<style type="text/css">
  .form-horizontal .control-label {
      margin-left: -30px;
  }
  .form-horizontal .controls{
      margin-right: 30px;
  }
  #documento_tipo_documento_id{
    width: 150px;
  }
  h4,h6{
    margin: 0px;
    padding: 0px;
  }
  .controls {
    padding-top: 5px;
  }
  </style>

<form class="form-horizontal">

  <div class="row">
    <h4>Datos Personales</h4>
  </div>


  <div class="row">
    <div class="span12">
      <div class="control-group success">
        <label class="control-label"><strong>Nombres y apellidos:</strong></label> 
          <div class="controls">       
            <%= @relevamiento.nombre_y_apellido %>
          </div>       
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="span6">
      <div class="control-group success">
        <label class="control-label"><strong>Tipo de documento:</strong></label>
        <div class="controls">
          <%= @relevamiento.tipo_de_documento %>
        </div>
      </div>
    </div>
    <div class="span6">
      <div class="control-group success">
        <label class="control-label"><strong>Número de documento:</strong></label>
        <div class="controls">
          <%= @relevamiento.nro_documento %>
        </div>
      </div>
    </div>
  </div>
 
  <div class="row">
    <div class="span6">
      <div class="control-group success">
        <label class="control-label"><strong>Escuela:</strong></label>
        <div class="controls">
          <%= @relevamiento.escuela %>
        </div>
      </div>
    </div>
    <div class="span6">
      <div class="control-group success">
        <label class="control-label"><strong>Nivel:</strong></label>
        <div class="controls">
          <%= @relevamiento.nivel %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <div class="control-group success">
        <label class="control-label"><strong>Tipo de gestión:</strong></label>
        <div class="controls">
          <%= @relevamiento.tipo_gestion %>
        </div>
      </div>
    </div>
  </div>
 
  <div class="row">
    <div class="span12">
      <div class="control-group success">
        <label class="control-label"><strong>Calle:</strong></label>
        <div class="controls">
          <%= @relevamiento.calle %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">    
    <div class="span3">
      <div class="control-group success">
        <label class="control-label"><strong>Nro:</strong></label>
        <div class="controls">
          <%= @relevamiento.nro %>
        </div>
      </div>
    </div>
    <div class="span3">
      <div class="control-group success">
        <label class="control-label"><strong>Piso:</strong></label>
        <div class="controls">
          <%= @relevamiento.piso %>
        </div>
      </div>
    </div>
     <div class="span3">
      <div class="control-group success">
        <label class="control-label"><strong>Depto:</strong></label>
        <div class="controls">
          <%= @relevamiento.depto %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <div class="control-group success">
        <label class="control-label"><strong>Localidad:</strong></label>
        <div class="controls">
          <%= @relevamiento.localidad %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <div class="control-group success">
        <label class="control-label"><strong>Servicio de transporte público que utiliza:</strong></label>
        <div class="controls">
          <%= @relevamiento.servicio_transporte %>
        </div>
      </div>
    </div>    
  </div>

  <div class="row">
    <div class="span12">
      <div class="control-group success">
        <label class="control-label"><strong>Teléfono de contacto:</strong></label>
        <div class="controls">
          <%= @relevamiento.telefono_contacto %>
        </div>
      </div>
    </div>    
  </div>

  <div class="row">
    <h4>Condición</h4>
  </div>

  <hr/>

  <div class="row">
    <div class="span12">
      <div class="control-group success">
        <label class="control-label"><strong>Indique su condición:</strong></label>
        <div class="controls">
          <%= @relevamiento.rol %>
        </div>
      </div>
    </div>    
  </div>

  <hr/>

  <% if @relevamiento.rol == "Alumno" %>

    <div class="row">
      <h4>Alumno</h4>
      <hr/>
    </div>

    <div id="alumno">
      <div class="row">
        <div class="span12">
          <div class="control-group success">
            <label class="control-label"><strong>Grado/Año:</strong></label>
            <div class="controls">
              <%= @relevamiento.grado_anio_alumno %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="span12">
          <div class="control-group success">
            <label class="control-label"><strong>Es regular:</strong></label>
            <div class="controls">
              <% if @relevamiento.regular == true %>
                Si
              <% else %>
                No
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div id="regular">
        <div class="row">
          <div class="span6">
            <div class="control-group success">
              <label class="control-label"><strong>Cantidad de cuadras a la escuela:</strong></label>
              <div class="controls">
                <%= @relevamiento.cant_cuadras %>
              </div>
            </div>
          </div>
          <div class="span6">
            <div class="control-group success">
              <label class="control-label"><strong>Cantidad de kilómetros a la escuela:</strong></label>
              <div class="controls">
                <%= @relevamiento.distancia_km %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% end %>

  <% if @relevamiento.rol == "Docente" %>

    <div class="row">
      <h4>Docente</h4>
      <hr/>
    </div>

    <div id="docente">
      <div class="row">
        <div class="span6">
          <div class="control-group success">
            <label class="control-label"><strong>Cantidad de cuadras a la escuela:</strong></label>
            <div class="controls">
              <%= @relevamiento.cant_cuadras %>
            </div>
          </div>
        </div>
        <div class="span6">
          <div class="control-group success">
            <label class="control-label"><strong>Cantidad de kilómetros a la escuela:</strong></label>
            <div class="controls">
              <%= @relevamiento.distancia_km %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <div class="control-group success">
            <label class="control-label"><strong>Es docente activo:</strong></label>
            <div class="controls">
              <% if @relevamiento.activo_pasivo_docente == true %>
                Si
              <% else %>
                No
              <% end %>
            </div>
          </div>
        </div>    
      </div>
      <div id="docente_activo">
        <div class="row">
          <div class="span12">
            <div class="control-group success">
              <label class="control-label"><strong>Cumple su función frente a grupo de alumnos:</strong></label>
              <div class="controls">
                <% if @relevamiento.frente_alumnos == true %>
                  Si
                <% else %>
                  No
                <% end %>
              </div>
            </div>
          </div>    
        </div>
        <div id="frente_alumno">
          <div class="row">
            <div class="span6">
              <div class="control-group success">
                <label class="control-label"><strong>Grado:</strong></label>
                <div class="controls">
                  <%= @relevamiento.grado_docente %>
                </div>
              </div>
            </div>
            <div class="span6">
              <div class="control-group success">
                <label class="control-label"><strong>Turno:</strong></label>
                <div class="controls">
                  <%= @relevamiento.turno_docente %>
                </div>
              </div>
            </div>     
          </div>
        </div>
      </div>
    </div>

  <% end %>

  <% if @relevamiento.rol == "Auxiliar de educación" %>

    <div class="row">
      <h4>Auxiliar de educación</h4>
      <hr/>
    </div>

    <div id="aux">
      <div class="row">
        <div class="span6">
          <div class="control-group success">
            <label class="control-label"><strong>Cantidad de cuadras a la escuela:</strong></label>
            <div class="controls">
              <%= @relevamiento.cant_cuadras %>
            </div>
          </div>
        </div>
        <div class="span6">
          <div class="control-group success">
            <label class="control-label"><strong>Cantidad de kilómetros a la escuela:</strong></label>
            <div class="controls">
              <%= @relevamiento.distancia_km %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="span12">
          <div class="control-group success">
            <label class="control-label"><strong>Es auxiliar activo:</strong></label>
            <div class="controls">
              <% if @relevamiento.activo_pasivo_aux == true %>
                Si
              <% else %>
                No
              <% end %>
            </div>
          </div>
        </div>    
      </div>
      <div id="aux_activo">
        <div class="row">
          <div class="span12">
            <div class="control-group success">
              <label class="control-label"><strong>Lugar donde cumple su función:</strong></label>
              <div class="controls">
                <%= @relevamiento.lugar_auxiliares %>
              </div>
            </div>
          </div>    
        </div>
      </div>
    </div>

  <% end %>

</form>

<%= link_to 'Editar', edit_relevamiento_path(@relevamiento), :class => "btn btn-primary" %>
<button onclick="location.href='http://chubut.edu.ar'" class="btn btn-success">Finalizar</button>
<%= link_to 'Finalizar y cargar otro', new_relevamiento_path, :class => "btn btn-primary" %>

app/views/relevamientos/sitio_en_construccion.html.erb
<html>

 <head>

  <meta http-equiv="Refresh" content="0;url=http://www.chubut.edu.ar/soft/teg">

 </head>

</html>